// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-Tnv3pgJYXcof-X7ZDra_En17AAo0Vs',
    appId: '1:256339991844:web:8ce33701791faa914c27b1',
    messagingSenderId: '256339991844',
    projectId: 'fixit19',
    authDomain: 'fixit19.firebaseapp.com',
    storageBucket: 'fixit19.firebasestorage.app',
    measurementId: 'G-DMTHRF2TQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-pUhDrpnEbFXxW_Ug31bSEdDmMLkSuQ',
    appId: '1:256339991844:android:5ed0a2459eb87f974c27b1',
    messagingSenderId: '256339991844',
    projectId: 'fixit19',
    storageBucket: 'fixit19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFqkJ9KbTpFUPn4VPOodIfUeyjTyUsJWg',
    appId: '1:256339991844:ios:31b018b50ce6be4c4c27b1',
    messagingSenderId: '256339991844',
    projectId: 'fixit19',
    storageBucket: 'fixit19.firebasestorage.app',
    iosBundleId: 'com.example.fixitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFqkJ9KbTpFUPn4VPOodIfUeyjTyUsJWg',
    appId: '1:256339991844:ios:31b018b50ce6be4c4c27b1',
    messagingSenderId: '256339991844',
    projectId: 'fixit19',
    storageBucket: 'fixit19.firebasestorage.app',
    iosBundleId: 'com.example.fixitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu-Tnv3pgJYXcof-X7ZDra_En17AAo0Vs',
    appId: '1:256339991844:web:53e5a8a68bb623774c27b1',
    messagingSenderId: '256339991844',
    projectId: 'fixit19',
    authDomain: 'fixit19.firebaseapp.com',
    storageBucket: 'fixit19.firebasestorage.app',
    measurementId: 'G-327PW6X2GM',
  );

}